name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Create static site
        run: |
          # Create site directory
          mkdir -p _site
          
          # Copy static files
          cp -r public_html/static _site/
          
          # Process and copy HTML files
          python -c "
          import os
          import re
          
          def process_html(content):
              # Update static file paths
              content = content.replace('\"/static/', '\"/Waimak-Website/static/')
              return content
          
          # Process main templates
          os.makedirs('_site', exist_ok=True)
          
          # Copy and process home page
          with open('templates/home.html', 'r') as f:
              content = f.read()
          with open('_site/index.html', 'w') as f:
              f.write(process_html(content))
          
          # Copy and process other pages
          pages = ['about', 'approach', 'contact', 'partners', 'faq']
          for page in pages:
              os.makedirs(f'_site/{page}', exist_ok=True)
              with open(f'templates/{page}.html', 'r') as f:
                  content = f.read()
              with open(f'_site/{page}/index.html', 'w') as f:
                  f.write(process_html(content))
          
          # Copy navbar template
          with open('templates/navbar.html', 'r') as f:
              navbar = f.read()
          with open('_site/navbar.html', 'w') as f:
              f.write(process_html(navbar))
          "

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site 