name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask frozen-flask
          pip install -r requirements.txt

      - name: Create static site
        run: |
          mkdir -p _site/static
          cp -r public_html/static/* _site/static/
          python -c "
          from flask import Flask, url_for
          from flask_frozen import Freezer
          import os
          import re
          
          app = Flask(__name__, 
                     static_folder='public_html/static',
                     static_url_path='/Waimak-Website/static')
          
          freezer = Freezer(app)
          
          def process_template(content):
              # Update static file references
              content = content.replace('\"/static/', '\"/Waimak-Website/static/')
              return content
          
          @app.route('/')
          def home():
              with open('templates/home.html', 'r') as f:
                  content = f.read()
              return process_template(content)
          
          @app.route('/<page>')
          def pages(page):
              with open(f'templates/{page}.html', 'r') as f:
                  content = f.read()
              return process_template(content)
          
          if __name__ == '__main__':
              freezer.freeze()
          "

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site 